### ISSUE TITLE
Permissions Problem

### ISSUE THREAD

**Issue by BastianBalthasarBux** [cpsitgmbh/be_links#1]
I have found a problem with the permissions. If you select 'group' or 'user and group' you won't have the possibility to add the permission to certain group.
As soon as you switch the modules permission to 'user', the module appears on editing the permissons of a group.
Funny ... ;)

TYPO3 6.2.15, be_links from TER, version 0.1.0

**Comment by IchHabRecht** [comment]
This problem should be solved with the new release 0.2.0 of this extension. Sorry for the delay! Would you mind to test it.

**Comment by BastianBalthasarBux** [comment]
Sry for my delay too! Works now as expected, tested on TYPO3 Version 6.2.26
Thanks for fixing that! :-)
