### ISSUE TITLE
Compatibility with TYPO3 V8

### ISSUE THREAD

**Issue by claude27** [cpsitgmbh/be_links#14]
In TYPO3 V8, even when installing the compatibilty7 extension, the menu titles are generated but when clicking on an item you allways get an error: "Invalid configuration: "extensionName" is not set".  I think it has to do with this breaking change: 
[https://docs.typo3.org/typo3cms/extensions/core/8.7/Changelog/8.0/Breaking-72405-RemovedTraditionalBEModulesHandling.html](url)

I tried to solve it myself but unfortunately I wasn't successfull. Thank you for your help.

**Comment by IchHabRecht** [comment]
HI @claude27,

Currently the compatibility to TYPO3 8.7 is available in another branch https://github.com/CPS-IT/be_links/tree/add-compatibility-8. Would you mind to use that one for your testing?

Thank you very much.

**Comment by claude27** [comment]
Hi @IchHabRecht ,

thank you for your quick answer. I also tried this branch, but the same error occurs. I think the problem is located in this file: BootstrapHook.php

**Comment by claude27** [comment]
Hi @IchHabRecht,

thank you very much for your quick fix. It work's now perfectly in TYPO3 V. 8.7. You earn a bear from me. :-)

Greets,
Claude
