### ISSUE TITLE
Minimal documentation ?

### ISSUE THREAD

**Issue by gaumondp** [cpsitgmbh/be_links#3]
Just reading the description we're not even sure what it does. 

A few screenshots or sentences would help know if it's useful for mere mortals.

**Comment by IchHabRecht** [comment]
Would you mind to proof read the documentation?

**Comment by gaumondp** [comment]
Sure I will but be aware I'm not a native speaker. :)

As for the short description visible in TER : "Add page or web links as backend modules" I would suggest you hint a bit more about the purpose or possible usages. Something like: 

_"Add page or web links as backend modules like links to TSref, company wiki with help for editor, etc.."_

**Comment by IchHabRecht** [comment]
Sorry, this is a short description in the extension configuration which I will not change at the moment.
