### ISSUE TITLE
How am I supposed to create a link?

### ISSUE THREAD

**Issue by crochelt** [cpsitgmbh/be_links#5]
After installing your extension I can't find any option to create a link in the backend.

**Comment by IchHabRecht** [comment]
Just create a storage folder and add backend link items,

**Comment by IchHabRecht** [comment]
I added a small documentation for this extension. Would you mind to proof read?

**Comment by crochelt** [comment]
Thank you, I will. Might take a little though. I am sick right now. Will get to it asap!

Christine
