### ISSUE TITLE
Fatal error after installation, if devlog is installed

### ISSUE THREAD

**Issue by seirerman** [cpsitgmbh/be_links#9]
I get a fatal error when I install be_links, resulting in a broken backend:

> Uncaught TYPO3 Exception
> Serialization of 'Closure' is not allowed 
>Exception thrown in file /var/www/html/t3inn/typo3conf/ext/devlog/Classes/Domain/Repository/EntryRepository.php in line 254.

and 

> caller => 'TYPO3\CMS\Core\Database\DatabaseConnection::exec_SELECTquery' (60 chars)
>    ERROR => 'Table 't3inn.tx_belinks_link' doesn't exist' (43 chars)
>    lastBuiltQuery => 'SELECT * FROM tx_belinks_link WHERE hidden=0 AND deleted=0 AND type=1' (69 chars)
>    debug_backtrace => 'call_user_func#21 // {closure}# // TYPO3\CMS\Backend\Http\Application->ru
>       n#20 // TYPO3\CMS\Core\Core\Bootstrap->handleRequest#94 // TYPO3\CMS\Back
>       end\Http\BackendModuleRequestHandler->handleRequest#302 // TYPO3\CMS\Back
>       end\Http\BackendModuleRequestHandler->dispatchModule#92 // TYPO3\CMS\Extb
>       ase\Core\Bootstrap->run#214 // TYPO3\CMS\Extbase\Core\Bootstrap->handl
>       eRequest#193 // TYPO3\CMS\Extbase\Mvc\Web\BackendRequestHandler->handleRe
>       quest#206 // TYPO3\CMS\Extbase\Mvc\Dispatcher->dispatch#32 // TYPO3\CMS\E
>       xtbase\Mvc\Controller\ActionController->processRequest#86 // TYPO3\CMS\Ex
>       tbase\Mvc\Controller\ActionController->callActionMethod#176 // call_user_
>       func_array#283 // TYPO3\CMS\Extensionmanager\Controller\ActionController->
>       ;toggleExtensionInstallationStateAction# // TYPO3\CMS\Extensionmanager\Servi
>       ce\ExtensionManagementService->installExtension#92 // TYPO3\CMS\Extension
>       manager\Service\ExtensionManagementService->installDependencies#229 // TY
>       PO3\CMS\Extensionmanager\Utility\InstallUtility->install#367 // TYPO3\CMS
>       \Extensionmanager\Utility\InstallUtility->reloadCaches#188 // TYPO3\CMS\C
>       ore\Core\Bootstrap->loadExtensionTables#446 // TYPO3\CMS\Core\Core\Bootst
>       rap->runExtTablesPostProcessingHooks#975 // CPSIT\BeLinks\Hook\BootstrapH
>       ook->processData#1028 // CPSIT\BeLinks\Hook\BootstrapHook->addMainModu
>       les#40 // TYPO3\CMS\Core\Database\DatabaseConnection->exec_SELECTgetRows#
>       53 // TYPO3\CMS\Core\Database\DatabaseConnection->exec_SELECTquery#377 //
>        TYPO3\CMS\Core\Database\DatabaseConnection->debug#314' (1511 chars)

This only happens if the extension devlog is installed at the time of the be_links installation.

So I tried to create the table manually:

```
CREATE TABLE tx_belinks_link (
    uid int(11) unsigned DEFAULT '0' NOT NULL auto_increment,
    pid int(11) unsigned DEFAULT '0' NOT NULL,

    cruser_id int(11) unsigned DEFAULT '0' NOT NULL,
    crdate int(11) unsigned DEFAULT '0' NOT NULL,
    tstamp int(11) unsigned DEFAULT '0' NOT NULL,
    deleted tinyint(4) unsigned DEFAULT '0' NOT NULL,
    hidden tinyint(4) unsigned DEFAULT '0' NOT NULL,

    title varchar(255) DEFAULT '' NOT NULL,
    type int(11) unsigned DEFAULT '0' NOT NULL,
    url mediumtext DEFAULT '' NOT NULL,
    icon blob NOT NULL,
    authentication varchar(10) DEFAULT '' NOT NULL,
    parent varchar(30) DEFAULT '0' NOT NULL,

    PRIMARY KEY (uid),
    KEY parent (pid)
);
```

That's when I ran into the root of the problem:
- Invalid default value for 'uid'
- BLOB/TEXT column 'url' can't have a default value

Fixing those two lines in ext_tables.sql solved my problem.

**Comment by IchHabRecht** [comment]
Hi,

Thank you for the report. Would you mind to open a pull request with the solution you provided?

**Comment by IchHabRecht** [comment]
Thank you!
